name: Docker CI Pipeline

on:
  push:
    branches:
      - main 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: khabirhakim/e-banking-front-github:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
